package pl.piomin.services.aws.order.model;

import java.io.Serializable;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMarshalling;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import pl.piomin.services.aws.order.util.EnumMarshaller;

@DynamoDBTable(tableName = "order")
public class Order implements Serializable {

	private static final long serialVersionUID = 510923895974229721L;
	
	private String id;
	private String accountId;
	private String amount;
	private OrderType type;
	private String transactionPagseguro;
	private String data;
	private String statusPagseguro;	
	private String name;
	private String email;
	private String address01;
	private String city;
	private String state;
	private String zip;
	private String empresa;
	private String enderecoEmpresa;
	private String cidadeEmpresa;
	private String estadoEmpresa;
	private String cepEmpresa;
	private String telEmpresa;	
	private String pedido;	

	private List<String> bins;

	public Order() {
	
	}
	
	public Order(String accountId, String amount, String transactionPagseguro, String data, String statusPagseguro, List<String> bins, String email, String address01, String city, String estado, String cep, String empresa, String enderecoEmpresa, String cidadeEmpresa, String estadoEmpresa, String cepEmpresa, String telEmpresa, String pedido) {
		//this.id = id;
		this.accountId = accountId;
		this.amount = amount;
		this.type = OrderType.TRANSFER;
		this.transactionPagseguro = transactionPagseguro;
		this.data = data;
		this.statusPagseguro = statusPagseguro;
		this.pedido = pedido;		
		this.bins = bins;	
	}

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute(attributeName = "accountId")
	public String getAccountId() {
		return accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@DynamoDBAttribute(attributeName = "amount")
	public String getAmount() {
		return amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	@DynamoDBMarshalling(marshallerClass = EnumMarshaller.class)
	@DynamoDBAttribute(attributeName = "type")
	public OrderType getType() {
		return type;
	}

	public void setType(OrderType type) {
		this.type = type;
	}

	@DynamoDBAttribute(attributeName = "transactionPagseguro")
	public String getTransactionPagseguro() {
		return transactionPagseguro;
	}

	public void setTransactionPagseguro(String transactionPagseguro) {
		this.transactionPagseguro = transactionPagseguro;
	}	
	

	@DynamoDBAttribute(attributeName = "data")
	public String getData() {
		return data;
	}

	public void setData(String data) {
		this.data = data;
	
	}
	@DynamoDBAttribute(attributeName = "statusPagseguro")
	public String getStatusPagseguro() {
		return statusPagseguro;
	}

	public void setStatusPagseguro(String statusPagseguro) {
		this.statusPagseguro = statusPagseguro;
	}
	@DynamoDBAttribute(attributeName = "name")	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@DynamoDBAttribute(attributeName = "email")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	
	@DynamoDBAttribute(attributeName = "address01")
	public String getAddress01() {
		return address01;
	}

	public void setAddress01(String address01) {
		this.address01 = address01;
	}	
	
	@DynamoDBAttribute(attributeName = "city")
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}	
	
	@DynamoDBAttribute(attributeName = "state")
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}	
	
	@DynamoDBAttribute(attributeName = "zip")
	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}	
	
	@DynamoDBAttribute(attributeName = "empresa")
	public String getEmpresa() {
		return empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}	
	
	@DynamoDBAttribute(attributeName = "enderecoEmpresa")
	public String getEnderecoEmpresa() {
		return enderecoEmpresa;
	}

	public void setEnderecoEmpresa(String enderecoEmpresa) {
		this.enderecoEmpresa = enderecoEmpresa;
	}	
	
	@DynamoDBAttribute(attributeName = "cidadeEmpresa")
	public String getCidadeEmpresa() {
		return cidadeEmpresa;
	}

	public void setCidadeEmpresa(String cidadeEmpresa) {
		this.cidadeEmpresa = cidadeEmpresa;
	}	
	
	@DynamoDBAttribute(attributeName = "estadoEmpresa")
	public String getEstadoEmpresa() {
		return estadoEmpresa;
	}

	public void setEstadoEmpresa(String estadoEmpresa) {
		this.estadoEmpresa = estadoEmpresa;
	}	
	
	@DynamoDBAttribute(attributeName = "cepEmpresa")
	public String getCepEmpresa() {
		return cepEmpresa;
	}

	public void setCepEmpresa(String cepEmpresa) {
		this.cepEmpresa = cepEmpresa;
	}	
	
	@DynamoDBAttribute(attributeName = "telEmpresa")
	public String getTelEmpresa() {
		return telEmpresa;
	}

	public void setTelEmpresa(String telEmpresa) {
		this.telEmpresa = telEmpresa;
	}	
	@DynamoDBAttribute(attributeName = "bins")
	public List<String> getBins() {
		return bins;
	}

	public void setBins(List<String> bins) {
		this.bins = bins;
	}

	@DynamoDBAttribute(attributeName = "pedido")	
	public String getPedido() {
		return pedido;
	}

	public void setPedido(String pedido) {
		this.pedido = pedido;
	}	
	@DynamoDBDocument
	public class Bins {

	    private String id;
	    private String description;
	    private String price;
	    private String unit;
	    private String quantity;

	    public String getId() {
			return id;
		}
		public void setId(String id) {
			this.id = id;
		}
		public String getDescription() {
			return description;
		}
		public void setDescription(String description) {
			this.description = description;
		}
		public String getPrice() {
			return price;
		}
		public void setPrice(String price) {
			this.price = price;
		}
		public String getUnit() {
			return unit;
		}
		public void setUnit(String unit) {
			this.unit = unit;
		}
		public String getQuantity() {
			return quantity;
		}
		public void setQuantity(String quantity) {
			this.quantity = quantity;
		}


	}		
}
